version: '2'
services:
    portainer:
        image: portainer/portainer
        restart: always
        ports:
            - 29000:9000
            - 28000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
#    tlsverify:
#    tlscacert:
#        - /certs/myCa.pem
volumes:
    portainer_data:
